// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: openinventorymanager.proto

package openinventorymanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for creating an item
type ItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Item name
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`                                                                           // Where it’s stored
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                     // Optional description
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                   // Tags for categorization
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Arbitrary key-value metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInput) Reset() {
	*x = ItemInput{}
	mi := &file_openinventorymanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInput) ProtoMessage() {}

func (x *ItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_openinventorymanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInput.ProtoReflect.Descriptor instead.
func (*ItemInput) Descriptor() ([]byte, []int) {
	return file_openinventorymanager_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInput) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ItemInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemInput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request message for fetching a single item
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique item ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_openinventorymanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openinventorymanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_openinventorymanager_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request for listing multiple items
type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // Optional paging
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Optional paging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_openinventorymanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openinventorymanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_openinventorymanager_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Output message for a single item
type ItemOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique item ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemOutput) Reset() {
	*x = ItemOutput{}
	mi := &file_openinventorymanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemOutput) ProtoMessage() {}

func (x *ItemOutput) ProtoReflect() protoreflect.Message {
	mi := &file_openinventorymanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemOutput.ProtoReflect.Descriptor instead.
func (*ItemOutput) Descriptor() ([]byte, []int) {
	return file_openinventorymanager_proto_rawDescGZIP(), []int{3}
}

func (x *ItemOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemOutput) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ItemOutput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemOutput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemOutput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Output message for listing multiple items
type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemOutput          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_openinventorymanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openinventorymanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_openinventorymanager_proto_rawDescGZIP(), []int{4}
}

func (x *ListItemsResponse) GetItems() []*ItemOutput {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_openinventorymanager_proto protoreflect.FileDescriptor

const file_openinventorymanager_proto_rawDesc = "" +
	"\n" +
	"\x1aopeninventorymanager.proto\x12\x14openinventorymanager\"\xf9\x01\n" +
	"\tItemInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.openinventorymanager.ItemInput.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x10ListItemsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8b\x02\n" +
	"\n" +
	"ItemOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12J\n" +
	"\bmetadata\x18\x06 \x03(\v2..openinventorymanager.ItemOutput.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x11ListItemsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .openinventorymanager.ItemOutputR\x05items2\x94\x02\n" +
	"\x10InventoryManager\x12O\n" +
	"\n" +
	"CreateItem\x12\x1f.openinventorymanager.ItemInput\x1a .openinventorymanager.ItemOutput\x12Q\n" +
	"\aGetItem\x12$.openinventorymanager.GetItemRequest\x1a .openinventorymanager.ItemOutput\x12\\\n" +
	"\tListItems\x12&.openinventorymanager.ListItemsRequest\x1a'.openinventorymanager.ListItemsResponseBGZEopeninventorymanager/protos/openinventorymanager;openinventorymanagerb\x06proto3"

var (
	file_openinventorymanager_proto_rawDescOnce sync.Once
	file_openinventorymanager_proto_rawDescData []byte
)

func file_openinventorymanager_proto_rawDescGZIP() []byte {
	file_openinventorymanager_proto_rawDescOnce.Do(func() {
		file_openinventorymanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openinventorymanager_proto_rawDesc), len(file_openinventorymanager_proto_rawDesc)))
	})
	return file_openinventorymanager_proto_rawDescData
}

var file_openinventorymanager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_openinventorymanager_proto_goTypes = []any{
	(*ItemInput)(nil),         // 0: openinventorymanager.ItemInput
	(*GetItemRequest)(nil),    // 1: openinventorymanager.GetItemRequest
	(*ListItemsRequest)(nil),  // 2: openinventorymanager.ListItemsRequest
	(*ItemOutput)(nil),        // 3: openinventorymanager.ItemOutput
	(*ListItemsResponse)(nil), // 4: openinventorymanager.ListItemsResponse
	nil,                       // 5: openinventorymanager.ItemInput.MetadataEntry
	nil,                       // 6: openinventorymanager.ItemOutput.MetadataEntry
}
var file_openinventorymanager_proto_depIdxs = []int32{
	5, // 0: openinventorymanager.ItemInput.metadata:type_name -> openinventorymanager.ItemInput.MetadataEntry
	6, // 1: openinventorymanager.ItemOutput.metadata:type_name -> openinventorymanager.ItemOutput.MetadataEntry
	3, // 2: openinventorymanager.ListItemsResponse.items:type_name -> openinventorymanager.ItemOutput
	0, // 3: openinventorymanager.InventoryManager.CreateItem:input_type -> openinventorymanager.ItemInput
	1, // 4: openinventorymanager.InventoryManager.GetItem:input_type -> openinventorymanager.GetItemRequest
	2, // 5: openinventorymanager.InventoryManager.ListItems:input_type -> openinventorymanager.ListItemsRequest
	3, // 6: openinventorymanager.InventoryManager.CreateItem:output_type -> openinventorymanager.ItemOutput
	3, // 7: openinventorymanager.InventoryManager.GetItem:output_type -> openinventorymanager.ItemOutput
	4, // 8: openinventorymanager.InventoryManager.ListItems:output_type -> openinventorymanager.ListItemsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openinventorymanager_proto_init() }
func file_openinventorymanager_proto_init() {
	if File_openinventorymanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openinventorymanager_proto_rawDesc), len(file_openinventorymanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openinventorymanager_proto_goTypes,
		DependencyIndexes: file_openinventorymanager_proto_depIdxs,
		MessageInfos:      file_openinventorymanager_proto_msgTypes,
	}.Build()
	File_openinventorymanager_proto = out.File
	file_openinventorymanager_proto_goTypes = nil
	file_openinventorymanager_proto_depIdxs = nil
}
